name: race_in_space
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  awesome_extensions: ^2.0.21
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  flame: ^1.28.0
  flame_behaviors: ^1.2.0
  flame_noise: ^0.3.2+9
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  flutter_shaders: ^0.1.3
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.0.0
  oktoast: ^3.4.0
  package_info_plus: ^8.3.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  watch_it: ^1.6.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/nebulae_gas.frag
    - assets/shaders/gas_planet.frag
    - assets/shaders/dry_planet.frag
    - assets/shaders/gravity_bubble.frag
    - assets/shaders/solar.frag

  fonts:
    - family: at01
      fonts:
        - asset: assets/fonts/at01.ttf
    - family: montjuic
      fonts:
        - asset: assets/fonts/montjuic.ttf
    - family: lana_pixel
      fonts:
        - asset: assets/fonts/lana_pixel.ttf
